[colors.bright]
black = "#666666"
blue = "#3b8eea"
cyan = "#29b8db"
green = "#23d18b"
magenta = "#d670d6"
red = "#f14c4c"
white = "#e5e5e5"
yellow = "#f5f543"

[colors.normal]
black = "#000000"
blue = "#2472c8"
cyan = "#11a8cd"
green = "#0dbc79"
magenta = "#bc3fbc"
red = "#cd3131"
white = "#e5e5e5"
yellow = "#e5e510"

[colors.primary]
background = "#000000"
foreground = "#cccccc"

[colors.selection]
background = "#565656"
text = "CellForeground"

[font]
size = 16.0

[font.offset]
x = 0
y = 5

[window]
decorations = "buttonless"
opacity = 1.0

[window.padding]
x = 5
y = 5
